"$schema" = 'https://starship.rs/config-schema.json'


format = '$time$all$character'
command_timeout = 100000

[git_status]
ahead = '⇡${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'

[git_metrics]
added_style = 'bold blue'
format = '[+$added]($added_style)/[-$deleted]($deleted_style) '

[memory_usage]
disabled = true
threshold = -1
symbol = '🚘'
format = '$symbol [${ram_pct}( |${swap})]($style)'
style = 'bold #15F5BA'


[time]
disabled = false
format = '🕙[\[$time\]]($style) '
time_format = '%T'
utc_time_offset = '+7'



[username]
style_user = 'white bold'
style_root = 'black bold'
format = '🌈 [$user]($style) | '
disabled = false
show_always = true

[git_branch]
symbol = '🌱 '
truncation_length = 70
truncation_symbol = '...'

[package]
disabled = true


[gcloud]
disabled = true


[openstack]
disabled = true

[container]
disabled = true

[docker_context]
disabled = true

